services:

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_USER: erik
      POSTGRES_PASSWORD: erik
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - local

  rabbit:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbit:/var/lib/rabbit/data
    networks:
      - local

  nats:
    image: nats
    restart: unless-stopped
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    volumes:
      - nats:/var/lib/nats/data
    networks:
      - local

  redis:
    image: redis/redis-stack:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis:/var/lib/redis/data
    networks:
      - local

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: erik
      MONGO_INITDB_ROOT_PASSWORD: erik
    networks:
      - local
  
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-1}
    volumes:
      - "./volume/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - local

volumes:
  db:
    driver: local
  rabbit:
    driver: local
  mongo:
    driver: local
  nats:
    driver: local
  redis:
    driver: local

networks:
  local:
    name: 'local'
    driver: bridge
